/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.InvoiceButtonsActionListener;
import controller.InvoiceMenuActionListener;
import controller.InvoiceSelectLineListeners;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import model.HeaderTable;
import model.InvoiceHeader;
import model.InvoiceLine;

/**
 *
 * @author Amany.Atef
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InvoiceHeaderTablejTable1 = new javax.swing.JTable();
        CreateInvoicejButton1 = new javax.swing.JButton();
        DeleteInvoicejButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InvoiceLinejTable2 = new javax.swing.JTable();
        CreateNewLinejButton3 = new javax.swing.JButton();
        DeleteLinejButton4 = new javax.swing.JButton();
        CustomerNamejLabel5 = new javax.swing.JLabel();
        InvoiceTotaljLabel6 = new javax.swing.JLabel();
        InvoiceDatejLabel7 = new javax.swing.JLabel();
        InvoiceNumjLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoadFilesjMenuItem3 = new javax.swing.JMenuItem();
        SaveFilejMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InvoiceHeaderTablejTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        InvoiceHeaderTablejTable1.setName("Invoice HeaderTable"); // NOI18N
        InvoiceHeaderTablejTable1.setOpaque(false);
        InvoiceHeaderTablejTable1.getSelectionModel().addListSelectionListener(selectLineListener);
        jScrollPane1.setViewportView(InvoiceHeaderTablejTable1);

        CreateInvoicejButton1.setLabel("Create Invoice");
        CreateInvoicejButton1.addActionListener(buttonsListener);

        DeleteInvoicejButton2.setLabel("Delete Invoice");
        DeleteInvoicejButton2.addActionListener(buttonsListener);

        jLabel1.setText("Invoice num");

        jLabel2.setText("Invoice date");

        jLabel3.setText("Customer name");

        jLabel4.setText("Invoice Total");

        InvoiceLinejTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(InvoiceLinejTable2);

        CreateNewLinejButton3.setLabel("New Line");
        CreateNewLinejButton3.addActionListener(buttonsListener);
        CreateNewLinejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewLinejButton3ActionPerformed(evt);
            }
        });

        DeleteLinejButton4.setLabel("Delete Line");
        DeleteLinejButton4.addActionListener(buttonsListener);

        jMenu1.setText("File");

        LoadFilesjMenuItem3.setText("LoadFiles");
        LoadFilesjMenuItem3.addActionListener(menuListener);
        LoadFilesjMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadFilesjMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(LoadFilesjMenuItem3);

        SaveFilejMenuItem4.setLabel("SaveFiles");
        SaveFilejMenuItem4.addActionListener(menuListener);
        SaveFilejMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFilejMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(SaveFilejMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InvoiceDatejLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(InvoiceNumjLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CustomerNamejLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(InvoiceTotaljLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(CreateInvoicejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteInvoicejButton2)
                        .addGap(207, 207, 207)
                        .addComponent(CreateNewLinejButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(DeleteLinejButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(InvoiceNumjLabel8))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(InvoiceDatejLabel7))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CustomerNamejLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InvoiceTotaljLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateNewLinejButton3)
                    .addComponent(DeleteLinejButton4)
                    .addComponent(DeleteInvoicejButton2)
                    .addComponent(CreateInvoicejButton1))
                .addGap(0, 171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadFilesjMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadFilesjMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadFilesjMenuItem3ActionPerformed

    private void SaveFilejMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFilejMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveFilejMenuItem4ActionPerformed

    private void CreateNewLinejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewLinejButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewLinejButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateInvoicejButton1;
    private javax.swing.JButton CreateNewLinejButton3;
    private javax.swing.JLabel CustomerNamejLabel5;
    private javax.swing.JButton DeleteInvoicejButton2;
    private javax.swing.JButton DeleteLinejButton4;
    private javax.swing.JLabel InvoiceDatejLabel7;
    private javax.swing.JTable InvoiceHeaderTablejTable1;
    private javax.swing.JTable InvoiceLinejTable2;
    private javax.swing.JLabel InvoiceNumjLabel8;
    private javax.swing.JLabel InvoiceTotaljLabel6;
    private javax.swing.JMenuItem LoadFilesjMenuItem3;
    private javax.swing.JMenuItem SaveFilejMenuItem4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
private InvoiceMenuActionListener menuListener =new InvoiceMenuActionListener(this) ;
private InvoiceButtonsActionListener buttonsListener =new InvoiceButtonsActionListener(this) ;

  public InvoiceButtonsActionListener getButtonsListener() {
        return buttonsListener;
    }
 //--------------------------------------------------------------------
private ArrayList <InvoiceHeader> InvoiceHeadersList;
private ArrayList <InvoiceLine> InvoiceLinesList;

    public void setInvoiceLinesList(ArrayList<InvoiceLine> InvoiceLinesList) {
        this.InvoiceLinesList = InvoiceLinesList;
    }

    public ArrayList<InvoiceLine> getInvoiceLinesList() {
        return InvoiceLinesList;
    }
private HeaderTable headerTable;
private HeaderTable LineTable;

    public HeaderTable getLineTable() {
        return LineTable;
    }

    public void setLineTable(HeaderTable LineTable) {
        this.LineTable = LineTable;
    }
private InvoiceSelectLineListeners selectLineListener = new InvoiceSelectLineListeners(this);
public static SimpleDateFormat NewDateFormate = new SimpleDateFormat("dd-MM-yyyy");

//----------------------------------------------------------
        /*HeadersTable Setter and Getter*/    
    public HeaderTable getHeaderTable() {
        return headerTable;
    }

    public void setHeaderTable(HeaderTable headerTable) {
        this.headerTable = headerTable;
    }
//------------------------------------------------------
         /*InvoiceHeadersList Setter and Getter*/
    public ArrayList<InvoiceHeader> getInvoiceHeadersList() {
        return InvoiceHeadersList;
    }

    public void setInvoiceHeadersList(ArrayList<InvoiceHeader> InvoiceHeadersList) {
        this.InvoiceHeadersList = InvoiceHeadersList;
    }
//-------------------------------------------------
     /*Loop on InvoiceHeadersList and get matched num with Line num */
    public InvoiceHeader getMatchedHeaderByNo(int no)
    {
        for(InvoiceHeader invheader :InvoiceHeadersList)
        {
            if(invheader.getNum()== no)
                return invheader;
        }
        return null;
    }
//-------------------------------------------------
    /*getter for headertable*/
    public JTable getInvoiceHeaderTablejTable1() {
        return InvoiceHeaderTablejTable1;
    }
    /*getter for labels*/
    public JLabel getCustomerNamejLabel5() {
        return CustomerNamejLabel5;
    }

    public JLabel getInvoiceDatejLabel7() {
        return InvoiceDatejLabel7;
    }

    public JLabel getInvoiceNumjLabel8() {
        return InvoiceNumjLabel8;
    }

    public JLabel getInvoiceTotaljLabel6() {
        return InvoiceTotaljLabel6;
    }

    public JTable getInvoiceLinejTable2() {
        return InvoiceLinejTable2;
    }


    
}
//-------------------------------------------------
